use VteamWork

ALTER TABLE tbl_QUESTION ADD IsRequired BIT NULL

ALTER TABLE [tbl_MODULE]
ADD UNIQUE (MODULE_NAME);


ALTER TABLE [tbl_QUESTION]
ADD UNIQUE (QUESTION_NAME);

update tbl_USER set TEAM_ID = NULL;
delete from tbl_TEAM_MODULE;
delete from [tbl_TEAM];

ALTER TABLE [tbl_TEAM]
ADD UNIQUE (TEAM_NAME);

ALTER TABLE [tbl_USER]
ADD UNIQUE (LOGIN_ID);

ALTER TABLE [dbo].[tbl_MODULE] ADD  PARENT_MODULE_ID [int] NULL;

ALTER TABLE [dbo].[tbl_MODULE]  WITH CHECK ADD  CONSTRAINT [FK_SubModule] FOREIGN KEY(PARENT_MODULE_ID)
REFERENCES [dbo].[tbl_MODULE] ([MODULE_ID])

ALTER TABLE [dbo].[tbl_MODULE] CHECK CONSTRAINT [FK_SubModule];

USE [VteamWork]
GO
SET IDENTITY_INSERT [dbo].[tbl_PAGE] ON 

INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (1, N'Student', N'Student.aspx', 1, 2, NULL, N'                                    ', 2, N'SCRIPT', CAST(N'2017-07-31' AS Date), N'SCRIPT', CAST(N'2017-07-31' AS Date))
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (2, N'Coach', N'Coach.aspx', 1, 2, NULL, N'                                    ', 3, N'SCRIPT', CAST(N'2017-07-31' AS Date), N'SCRIPT', CAST(N'2017-07-31' AS Date))
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (3, N'New User', N'User.aspx', 1, 2, NULL, NULL, 1, N'SCRIPT', CAST(N'2017-07-31' AS Date), N'SCRIPT', CAST(N'2017-07-31' AS Date))
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (4, N'Deactivate User', N'OldUser.aspx', 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (6, N'Create Team', N'Team.aspx', 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (7, N'Create Module', N'Module.aspx', 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (8, N'Add Question', N'Question.aspx', 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[tbl_PAGE] ([PAGE_ID], [PAGE_NAME], [PAGE_PATH], [APPLICATION_ID], [MENU_GROUP_ID], [PAGE_TYPE], [UPDATE_ID], [PAGE_SEQ], [CREATED_BY], [CREATED_ON], [UPDATED_BY], [UPDATED_ON]) VALUES (9, N'Assigning', N'AssignTeam.aspx', 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[tbl_PAGE] OFF

