USE [VteamWork]
GO

--ALTER TABLE [dbo].[tbl_QUESTION] DROP CONSTRAINT [FK_UserType]
--GO

ALTER TABLE [dbo].[tbl_QUESTION] ADD  [user_type_id] [int] NULL;


ALTER TABLE [dbo].[tbl_QUESTION]  WITH CHECK ADD  CONSTRAINT [FK_UserType] FOREIGN KEY(user_type_id)
REFERENCES [dbo].[tbl_USER_TYPE] ([USER_TYPE_ID])
GO
ALTER TABLE [dbo].[tbl_QUESTION] CHECK CONSTRAINT [FK_UserType]
GO
