USE [VteamWork]
GO

--ALTER TABLE [dbo].[tbl_QUESTION] DROP CONSTRAINT [FK_UserType]
--GO

ALTER TABLE [dbo].[tbl_QUESTION] DROP CONSTRAINT [FK_dbo.tbl_QUESTION_dbo.tbl_USER_USER_ID]
GO

ALTER TABLE [dbo].[tbl_QUESTION] DROP CONSTRAINT [FK_dbo.tbl_QUESTION_dbo.tbl_MODULE_MODULE_ID]
GO


ALTER TABLE [dbo].[tbl_ANSWER] DROP CONSTRAINT [FK_dbo.tbl_ANSWER_dbo.tbl_QUESTION_QUESTION_ID]
GO

/****** Object:  Table [dbo].[tbl_QUESTION]    Script Date: 9/5/2017 10:27:34 AM ******/
DROP TABLE [dbo].[tbl_QUESTION]
GO

/****** Object:  Table [dbo].[tbl_QUESTION]    Script Date: 9/5/2017 10:27:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbl_QUESTION](
	[QUESTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[QUESTION_NAME] [varchar](100) NULL,
	[QUESTION_DESCRITION] [varchar](100) NULL,
	[user_type_id] [int] NULL,
	[USER_ID] [int] NULL,
	[MODULE_ID] [int] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[CREATED_ON] [date] NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[UPDATED_ON] [date] NULL,
 CONSTRAINT [PK_dbo.tbl_QUESTION] PRIMARY KEY CLUSTERED 
(
	[QUESTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[tbl_QUESTION]  WITH CHECK ADD  CONSTRAINT [FK_dbo.tbl_QUESTION_dbo.tbl_MODULE_MODULE_ID] FOREIGN KEY([MODULE_ID])
REFERENCES [dbo].[tbl_MODULE] ([MODULE_ID])
GO

ALTER TABLE [dbo].[tbl_QUESTION] CHECK CONSTRAINT [FK_dbo.tbl_QUESTION_dbo.tbl_MODULE_MODULE_ID]
GO

ALTER TABLE [dbo].[tbl_QUESTION]  WITH CHECK ADD  CONSTRAINT [FK_dbo.tbl_QUESTION_dbo.tbl_USER_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[tbl_USER] ([USER_ID])
GO

ALTER TABLE [dbo].[tbl_QUESTION] CHECK CONSTRAINT [FK_dbo.tbl_QUESTION_dbo.tbl_USER_USER_ID]
GO

ALTER TABLE [dbo].[tbl_QUESTION]  WITH CHECK ADD  CONSTRAINT [FK_UserType] FOREIGN KEY([user_type_id])
REFERENCES [dbo].[tbl_USER_TYPE] ([USER_TYPE_ID])
GO

ALTER TABLE [dbo].[tbl_QUESTION] CHECK CONSTRAINT [FK_UserType]
GO

ALTER TABLE [dbo].[tbl_ANSWER]  WITH CHECK ADD  CONSTRAINT [FK_dbo.tbl_ANSWER_dbo.tbl_QUESTION_QUESTION_ID] FOREIGN KEY([QUESTION_ID])
REFERENCES [dbo].[tbl_QUESTION] ([QUESTION_ID])
GO
ALTER TABLE [dbo].[tbl_ANSWER] CHECK CONSTRAINT [FK_dbo.tbl_ANSWER_dbo.tbl_QUESTION_QUESTION_ID]
GO
