

USE [VteamWork]
GO

update tbl_USER set TEAM_ID = NULL
delete from tbl_TEAM_MODULE
delete from [tbl_TEAM]

ALTER TABLE [tbl_TEAM]
ADD UNIQUE (TEAM_NAME);


ALTER TABLE [tbl_USER]
ADD UNIQUE (LOGIN_ID);
GO
ALTER TABLE [dbo].[tbl_MODULE] ADD  PARENT_MODULE_ID [int] NULL;

ALTER TABLE [dbo].[tbl_MODULE]  WITH CHECK ADD  CONSTRAINT [FK_SubModule] FOREIGN KEY(PARENT_MODULE_ID)
REFERENCES [dbo].[tbl_MODULE] ([MODULE_ID])
GO
ALTER TABLE [dbo].[tbl_MODULE] CHECK CONSTRAINT [FK_SubModule]
GO